# Generated by Django 4.2.10 on 2024-03-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("Mobilenumber", models.IntegerField()),
                ("password", models.CharField(max_length=50)),
                ("Adress", models.TextField()),
            ],
        ),
    ]
