# Generated by Django 4.2.10 on 2024-03-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_rename_adress_register_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="register",
            name="Mobilenumber",
            field=models.CharField(max_length=10),
        ),
    ]
