# Generated by Django 4.2.10 on 2024-03-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_category_alter_register_mobilenumber"),
    ]

    operations = [
        migrations.RenameModel(old_name="Category", new_name="catgo",),
    ]
