# Generated by Django 4.2.10 on 2024-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="feedbk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("feedback", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="feedback",),
    ]
