# Generated by Django 4.2.10 on 2024-03-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_feedbk_delete_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="proimg")),
                ("qty", models.IntegerField()),
                ("discription", models.TextField()),
                ("price", models.CharField(max_length=5)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.catgo"
                    ),
                ),
            ],
        ),
    ]
