# Generated by Django 4.2.10 on 2024-03-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_rename_products_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productid", models.CharField(max_length=5)),
                ("userid", models.CharField(max_length=5)),
                ("quantity", models.IntegerField()),
                ("totalprice", models.CharField(max_length=5)),
                ("orderid", models.CharField(max_length=5)),
            ],
        ),
    ]
