# Generated by Django 4.2.10 on 2024-03-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_cart"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="totalprice",),
    ]
