# Generated by Django 4.2.10 on 2024-03-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_remove_cart_totalprice"),
    ]

    operations = [
        migrations.RenameModel(old_name="feedbk", new_name="feedb",),
    ]
