# Generated by Django 4.2.10 on 2024-03-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_cart_totalprice_delete_userpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("Mobilenumber", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=50)),
                ("Address", models.TextField()),
                ("tob", models.CharField(max_length=50)),
            ],
        ),
    ]
