# Generated by Django 4.2.10 on 2024-03-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_vendor"),
    ]

    operations = [
        migrations.RenameModel(old_name="vendor", new_name="vendors",),
    ]
