# Generated by Django 4.2.10 on 2024-04-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_product_vendorid"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=10)),
                ("productid", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("pincode", models.CharField(max_length=6)),
                ("paymenttype", models.CharField(max_length=20)),
                ("transactionid", models.CharField(max_length=50)),
                ("datetime", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
